COMMON: &common

  DEBUG: False
  SECRET_KEY: 'its-a-setup'
  SECURITY_PASSWORD_HASH: bcrypt
  SECURITY_PASSWORD_SALT: 'its-a-setup'

DEVELOPMENT: &development
  <<: *common
  DEBUG: True
  SITE_URL: 'localhost:4999'
  SQLALCHEMY_DATABASE_URI: 'ordbok_local_config'
