COMMON: &common

  DEBUG: False
  SECRET_KEY: 'its-a-setup'
  REDIS_CHANNEL: 'chat'

DEVELOPMENT: &development
  <<: *common
  DEBUG: True
  SITE_URL: 'localhost:4999'
  REDIS_URL: 'ordbok_local_config'

PRODUCTION: &production
  <<: *common
  REDIS_URL: 'ordbok_env_config_rediscloud_url'
  SITE_URL: 'flaskchat.skien.cc'